language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -e .
  - pip install -r requirements.txt 
script:
  - py.test --cov . --cov-report xml:coverage.xml

env:
  global:
    - CC_TEST_REPORTER_ID=7e609de8d70e3bf3d93a371b98ed3f463c18dc6c960f627866be63fec365f263

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
